#!/bin/bash

find $1 -type f -name '*' | while read FILE ; do
	newfile="$(echo ${FILE} |sed -e 's/ ... BluRay1080p ! 2015//')" ;
	newfile="$(echo ${newfile} |sed -e 's/ ... BluRay1080p ! 2016//')" ;
	newfile="$(echo ${newfile} |sed -e 's/ ... WebDl1080p ! 2017/ WEB-DL 1080p/')" ;
	newfile="$(echo ${newfile} |sed -e 's/ ... WebDl1080p ! 2018/ WEB-DL 1080p/')" ;
	mv "${FILE}" "${newfile}" ;
done 
