#!/bin/zsh

if [ -z "$1" ]; then
	export DOCKER_HOST=unix:///var/run/docker.sock
	unset POWERLEVEL9K_CUSTOM_SWARM
	unset http_proxy
else
	NODE=${2:-1}

	case $1:u in
	DMZ)
		export DOCKER_HOST=tcp://swarm$NODE.dmz.home.lecat.network:2375
		export DOCKER_ENV=dmz
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	SECURE)
		export DOCKER_HOST=tcp://swarm$NODE.secure.home.lecat.network:2375
		export DOCKER_ENV=secure
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	ZABBIX)
		export DOCKER_HOST=tcp://zabbix.secure.home.lecat.network:2375
		export DOCKER_ENV=zabbix
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	ZBX-PROXY-SECURE)
		export DOCKER_HOST=tcp://zabbix-proxy.secure.home.lecat.network:2375
		export DOCKER_ENV=zbx-proxy-secure
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	ZBX-PROXY-HW)
		export DOCKER_HOST=tcp://zabbix-proxy-hw.secure.home.lecat.network:2375
		export DOCKER_ENV=zbx-proxy-hw
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	ZBX-PROXY-DMZ)
		export DOCKER_HOST=tcp://zabbix-proxy.dmz.home.lecat.network:2375
		export DOCKER_ENV=zbx-proxy-dmz
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	STORAGE)
		export DOCKER_HOST=tcp://storage.secure.home.lecat.network:2375
		export DOCKER_ENV=storage
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	PLEX)
		export DOCKER_HOST=tcp://plex.secure.home.lecat.network:2375
		export DOCKER_ENV=plex
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	TRANSCODER)
		export DOCKER_HOST=tcp://transcoder.secure.home.lecat.network:2375
		export DOCKER_ENV=transcoder
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	SMOKEPING-HOME)
		export DOCKER_HOST=tcp://smokeping.dmz.home.lecat.network:2375
		export DOCKER_ENV=smokeping-home
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	SMOKEPING-OSC)
		export DOCKER_HOST=tcp://smokeping.dmz.osc.lecat.network:2375
		export DOCKER_ENV=smokeping-osc
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	LG)
		export DOCKER_HOST=tcp://lg.dmz.home.lecat.network:2375
		export DOCKER_ENV=lg
		export http_proxy=http://adm.secure.home.lecat.network:3128
		;;
	NS-IOT)
		export DOCKER_HOST=tcp://ns.iot.home.lecat.network:2375
		export DOCKER_ENV=ns-iot
		export http_proxy=http://adm.secure.home.lecat.network:3128
        ;;
	esac

	export POWERLEVEL9K_CUSTOM_SWARM_BACKGROUND="white"
	export POWERLEVEL9K_CUSTOM_SWARM="echo 🐳 $DOCKER_ENV:u"
fi
